import { ApiProperty } from '@nestjs/swagger';
import { Transform } from 'class-transformer';
import { IsEmail, IsNotEmpty, IsPhoneNumber, IsString } from 'class-validator';
import { AccountStatus, AccountType, BloodGroup, Genotype } from 'libs/common/src/constants/enums';
import {
  toLowerCaseTransformer,
  trimTransformer,
} from 'libs/common/src/helpers/local-class-validator';

export class UpdateFCMTokenDTO {
  @ApiProperty({
    example: '1733689739675',
    description: 'FCM token for push notifications generated by mobile device.',
  })
  @IsString()
  @IsNotEmpty()
  fcmToken: string;
}

export class UpdateAccountPasswordDTO {
  @ApiProperty({
    example: 'Password123',
    description: 'Current account password.',
  })
  @IsString()
  @IsNotEmpty()
  currentPassword: string;

  @ApiProperty({
    example: 'Password@123',
    description: 'New account password.',
  })
  @IsString()
  @IsNotEmpty()
  newPassword: string;
}

export class UpdateAccountEmailDTO {
  @ApiProperty({
    example: 'kunle@gmail.com',
    description: 'New account email.',
  })
  @IsEmail()
  @IsNotEmpty()
  @Transform(({ value }) => trimTransformer(toLowerCaseTransformer(value)))
  newEmail: string;
}

export class VerifyNewAccountEmailDTO {
  @ApiProperty({
    example: '3950',
    description: 'Activation token (OTP)',
  })
  @IsString()
  @IsNotEmpty()
  otp: string;
}

export class UpdateAccountPhoneDTO {
  @ApiProperty({
    example: '+2349093920293',
    description: 'New account phone.',
  })
  @IsNotEmpty()
  @IsPhoneNumber()
  @Transform(({ value }) => trimTransformer(value))
  newPhone: string;

  @ApiProperty({
    example: 'Password123',
    description: 'Account password.',
  })
  @IsString()
  @IsNotEmpty()
  password: string;
}
